'use client';
import { useState,useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Plus, ArrowUpRight, ArrowRight, Factory, GraduationCap, Shield, Package, FolderOpen, FileText, Layers, Activity, Search, Sparkles, RefreshCw } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { CreateWorkspace } from '@/components/create-workspace';
import { api,industries,Workspace,supabase } from '@/lib/api';
const Icons=[Factory,GraduationCap,Shield,Package];
export default function Dashboard(){
 const [workspaces,setWorkspaces]=useState<Workspace[]>([]),[create,setCreate]=useState(false),[industry,setIndustry]=useState('Manufacturing'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState('');const router=useRouter();
 useEffect(()=>{let active=true;(async()=>{try{if(!supabase){router.replace('/login');return;}if(supabase){const {data}=await supabase.auth.getSession();if(!data.session){router.replace('/login');return;}}const ws=await api<Workspace[]>('/workspaces');if(active){setWorkspaces(ws);}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}const i=new URLSearchParams(location.search).get('industry');if(i&&industries.some(x=>x.name===i)){setIndustry(i);setCreate(true);}})();return()=>{active=false;};},[router]);
 const fileCount=workspaces.reduce((n,w)=>n+(w.file_count||0),0),readyCount=workspaces.reduce((n,w)=>n+(w.ready_count||0),0),processingCount=workspaces.reduce((n,w)=>n+(w.processing_count||0),0);const visible=workspaces.filter(w=>(w.name+' '+w.industry).toLowerCase().includes(search.toLowerCase()));
 return <AppShell onCreate={()=>setCreate(true)}><header className="app-topbar"><span>Workspace <span>/</span> <strong>Dashboard</strong></span></header><div className="dashboard-content"><div className="page-heading"><div><span className="overline">YOUR INTELLIGENCE COMMAND CENTER</span><h1>See the bigger picture<span className="cyan">.</span></h1><p>Connect your evidence. Find your answers. Move forward with clarity.</p></div><button onClick={()=>setCreate(true)} className="button primary"><Plus size={16}/>New workspace</button></div>{error&&<div role="alert" className="error-banner">{error}<button onClick={()=>location.reload()}><RefreshCw size={14}/>Retry</button></div>}
 <div className="stats-grid">{[{label:'Active workspaces',value:workspaces.length,Icon:FolderOpen,note:'Your connected investigations'},{label:'Evidence files',value:fileCount,Icon:Layers,note:'Across all your workspaces'},{label:'Files processed',value:readyCount,Icon:FileText,note:'Extracted and indexed'},{label:'Processing queue',value:processingCount,Icon:Activity,note:'Ready for background processing'}].map(s=><div className="stat-card" key={s.label}><div><span>{s.label}</span><s.Icon size={17}/></div><strong>{loading?'—':s.value}</strong><small>{s.note}</small></div>)}</div>
 <section className="dashboard-section"><div className="subheading"><div><h2>Your workspaces <span className="count">{workspaces.length}</span></h2><p>Pick up where you left off.</p></div><div className="search-box"><Search size={16}/><input aria-label="Search workspaces" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search workspaces…"/></div></div>{loading?<div className="loading-card">Loading your workspaces…</div>:visible.length?<div className="workspace-grid">{visible.map(w=>{const i=Math.max(0,industries.findIndex(x=>x.name===w.industry));const Icon=Icons[i];return <Link className="workspace-card" href={'/workspace/'+w.id} key={w.id} style={{'--industry-color':industries[i].color} as React.CSSProperties}><div className="industry-top"><span className="industry-icon"><Icon size={21}/></span><span className="workspace-type">{w.industry}</span><ArrowUpRight size={16}/></div><h3>{w.name}</h3><p>{w.description||'Add evidence to begin connecting the story.'}</p><div className="workspace-card-footer"><span><Layers size={13}/>{w.file_count||0} files</span><span>{new Date(w.created_at).toLocaleDateString()}</span></div></Link>;})}</div>:<div className="empty-state"><FolderOpen size={32}/><h3>{search?'No matching workspaces':'Make room for your first insight.'}</h3><p>{search?'Try a different search.':'Create a workspace and upload your evidence to get started.'}</p><button className="button secondary" onClick={()=>setCreate(true)}>Create workspace <Plus size={14}/></button></div>}</section>
 <section className="dashboard-section"><div className="subheading"><div><h2>Built for your world</h2><p>One shared engine. Four focused experiences.</p></div></div><div className="industry-grid dashboard-industries">{industries.map((v,i)=>{const Icon=Icons[i];return <button className="industry-card" key={v.name} onClick={()=>{setIndustry(v.name);setCreate(true);}} style={{'--industry-color':v.color} as React.CSSProperties}><div className="industry-top"><span className="industry-icon"><Icon size={22}/></span><ArrowUpRight size={16}/></div><h3>{v.name}</h3><p>{v.description}</p><span className="card-link">Create workspace <ArrowRight size={13}/></span></button>;})}</div></section></div>{create&&<CreateWorkspace onClose={()=>setCreate(false)} initial={industry}/>}</AppShell>;
}
