'use client';
import SignInModal from '@/components/sign-in-modal';
import SpecularButton from '@/components/SpecularButton/SpecularButton';
import dynamic from 'next/dynamic';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Play, FileText, Image, AudioLines, Video, Database, ShieldCheck, Network, ScanLine, Check, Factory, GraduationCap, Package, Shield, ChevronDown, Menu, X, Sparkles, Layers, Fingerprint, MousePointer2 } from 'lucide-react';
import { Brand } from '@/components/brand';
import { industries } from '@/lib/api';
import LiquidLandingBackground from '@/components/liquid-landing-background';
const NeuralCore=dynamic(()=>import('@/components/neural-core'),{ssr:false});
const icons=[FileText,Image,AudioLines,Video,Database];
const modalityNames=['Documents','Images','Audio','Video','Structured data'];
const industryIcons=[Factory,GraduationCap,Shield,Package];
export default function Home(){
  const [menu,setMenu]=useState(false),[signIn,setSignIn]=useState(false);
  return <main className="landing"><LiquidLandingBackground/>{signIn&&<SignInModal onClose={()=>setSignIn(false)}/>}
    <header className="site-header"><div className="container nav"><Brand/><nav className={menu?'nav-links open':'nav-links'}><a href="#platform" onClick={()=>setMenu(false)}>Platform</a><a href="#industries" onClick={()=>setMenu(false)}>Solutions <ChevronDown size={12}/></a><a href="#how-it-works" onClick={()=>setMenu(false)}>How it works</a><a href="#trust" onClick={()=>setMenu(false)}>Why Evidence</a></nav><div className="nav-actions"><SpecularButton size="sm" className="mobile-menu icon-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</SpecularButton></div></div></header>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow-pill"><span className="live-dot"/> THE NEXT GENERATION OF MULTIMODAL AI <ArrowUpRight size={12}/></div><h1>Every format.<br/>One <span className="gradient-text">intelligence.</span></h1><p className="hero-description">Your evidence is everywhere.<br/>Your answers should be in one place.</p><p className="hero-subcopy">Transform disconnected videos, audio, documents, images, and structured data into connected, explainable intelligence.</p><div className="hero-actions"><SpecularButton className="landing-launch" tint="#9160c7" tintOpacity={0.65} lineColor="#ffffff" baseColor="#b497cf" onClick={()=>setSignIn(true)}>Launch Intelligence Workspace <ArrowRight size={17}/></SpecularButton><SpecularButton className="landing-explore" size="md" onClick={()=>{location.hash="how-it-works";}}><span className="play-circle"><Play size={11} fill="currentColor"/></span> Explore how it works</SpecularButton></div><div className="hero-assurance"><span><Check size={13}/> Every answer, source-backed</span><span><ShieldCheck size={13}/> Your evidence stays yours</span></div></div>
    <div className="hero-visual"><div className="orb-glow"/><NeuralCore/><div className="core-label"><span className="live-dot"/><span>INTELLIGENCE CORE</span></div><div className="floating-node node-doc"><FileText/><span>Documents<small>Context, extracted.</small></span></div><div className="floating-node node-video"><Video/><span>Video<small>Every moment matters.</small></span></div><div className="floating-node node-image"><Image/><span>Images<small>Beyond what you see.</small></span></div><div className="floating-node node-audio"><AudioLines/><span>Audio<small>Turn voices into insights.</small></span></div><div className="floating-node node-data"><Database/><span>Structured data<small>Find the signals.</small></span></div><div className="visual-caption"><span className="tiny-cross">+</span> CONNECTING THE DOTS. REVEALING THE STORY. <span className="tiny-cross">+</span></div></div></section>
    <section className="modality-strip container" id="platform"><span className="strip-label">MANY INPUTS.<br/><strong>ONE CONNECTED PICTURE.</strong></span><div>{modalityNames.map((name,i)=>{const Icon=icons[i];return <span key={name}><Icon size={19}/>{name}</span>;})}</div><span className="format-caption">Any evidence.<br/>Real understanding.</span></section>
    <section className="section container" id="industries"><div className="section-heading"><div><span className="overline"><span/> BUILT FOR YOUR WORLD</span><h2>One engine. <span className="muted">Every industry.</span></h2></div><p>Different challenges. The same power to connect<br className="desktop-break"/> evidence and uncover what matters.</p></div><div className="industry-grid">{industries.map((industry,i)=>{const Icon=industryIcons[i];return <div className="industry-card" key={industry.name} style={{'--industry-color':industry.color} as React.CSSProperties}><div className="industry-top"><span className="industry-icon"><Icon size={23}/></span><ArrowUpRight size={17}/></div><span className="card-eyebrow">{industry.eyebrow}</span><h3>{industry.name}</h3><p>{industry.description}</p><span className="card-link">Connected evidence <Check size={14}/></span></div>;})}</div></section>
    <section className="section how-section container" id="how-it-works"><div className="section-heading"><div><span className="overline"><span/> FROM INFORMATION TO INTELLIGENCE</span><h2>Evidence in. <span className="muted">Clarity out.</span></h2></div></div><div className="steps-grid">{[{title:'Bring your evidence',text:'Upload your files in any supported format. Give disconnected information a shared home.',Icon:Layers},{title:'Connect the context',text:'Extract, index, and connect source material across formats in one workspace.',Icon:Network},{title:'Ask. Understand. Act.',text:'Explore cited answers, inspect original sources, and export a report for review.',Icon:Sparkles}].map((step,i)=><div className="step" key={step.title}><div className="step-line"><span>0{i+1}</span><div/><step.Icon size={21}/></div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
    <section className="section container" id="trust"><div className="section-heading"><div><span className="overline"><span/> INTELLIGENCE, WITH ACCOUNTABILITY</span><h2>Clarity needs <span className="muted">a foundation.</span></h2></div></div><div className="trust-grid">{[{Icon:Fingerprint,title:'Private by design',text:'Workspace authorization and private file storage keep your investigations contained.'},{Icon:ScanLine,title:'Evidence, not guesswork',text:'Source-linked passages and honest uncertainty help you verify every interpretation.'},{Icon:MousePointer2,title:'The context is one click away',text:'Open the original document, image, or media segment directly from a citation.'}].map(f=><div className="trust-card" key={f.title}><f.Icon size={25}/><h3>{f.title}</h3><p>{f.text}</p></div>)}</div></section>
    <section className="container final-cta"><div className="cta-grid-glow"/><span className="overline">YOUR NEXT ANSWER IS ALREADY IN YOUR EVIDENCE</span><h2>Bring it all together.</h2><p>One Intelligence. Every Format. Infinite Possibilities.</p></section>
    <footer className="container footer"><Brand/><span>Connected evidence. Explainable intelligence.</span><div><a href="#trust">Security</a><span>© {new Date().getFullYear()} EVIDENCE.AI</span></div></footer>
  </main>;
}



