'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { LayoutDashboard, FolderOpen, MessageSquare, Network, Clock3, Lightbulb, FileBarChart, Settings, ChevronRight, Plus, Menu, X, LogOut, Sparkles } from 'lucide-react';
import { Brand } from './brand';
import { supabase } from '@/lib/api';
export const tabs=[{id:'overview',label:'Overview',Icon:LayoutDashboard},{id:'evidence',label:'Evidence Library',Icon:FolderOpen},{id:'assistant',label:'AI Assistant',Icon:MessageSquare},{id:'graph',label:'Knowledge Graph',Icon:Network},{id:'timeline',label:'Timeline',Icon:Clock3},{id:'insights',label:'Insights',Icon:Lightbulb},{id:'reports',label:'Reports',Icon:FileBarChart},{id:'settings',label:'Settings',Icon:Settings}];
export function AppShell({children,workspace,tab,onTab,onCreate}:{children:React.ReactNode;workspace?:string;tab?:string;onTab?:(t:string)=>void;onCreate?:()=>void}){
 const [open,setOpen]=useState(false);const router=useRouter();
 return <div className="app-shell"><div className="mobile-appbar"><Brand small/><button className="icon-button" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<button aria-label="Close navigation" className="sidebar-overlay" onClick={()=>setOpen(false)}/>}
 <aside className={`sidebar ${open?'visible':''}`}><Brand/><div className="workspace-picker"><span className="workspace-avatar">E</span><div><strong>{workspace||'Your workspace'}</strong><small>Intelligence platform</small></div><ChevronRight size={14}/></div><span className="sidebar-label">WORKSPACE</span><nav className="sidebar-nav">{workspace?tabs.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>{onTab?.(item.id);setOpen(false);}}><item.Icon size={17}/>{item.label}{item.id==='assistant'&&<span className="nav-new">AI</span>}</button>):<><Link className="active" href="/dashboard"><LayoutDashboard size={17}/>Dashboard</Link><button onClick={onCreate}><Plus size={17}/>Create workspace</button></>}</nav>{workspace&&<Link className="back-dashboard" href="/dashboard"><LayoutDashboard size={15}/>All workspaces</Link>}<div className="sidebar-bottom"><div className="sidebar-tip"><Sparkles size={20}/><strong>A bigger picture starts here.</strong><p>Bring every source into one connected workspace.</p>{workspace?<button onClick={()=>onTab?.('evidence')}>Add evidence <Plus size={13}/></button>:<button onClick={onCreate}>Create workspace <Plus size={13}/></button>}</div><div className="profile"><span className="user-avatar">EA</span><div><Link href="/account"><strong>Profile &amp; account</strong></Link><small>{'Your account'}</small></div><button className="icon-button" aria-label="Sign out" onClick={async()=>{await supabase?.auth.signOut();router.push('/login');}}><LogOut size={16}/></button></div></div></aside><div className="app-main">{children}</div></div>;
}
