'use client';
import {DotsRing} from './ui/dots-ring';
import {useEffect,useState} from 'react';
import {Mail,Check} from 'lucide-react';
import {pulse,Draft,Customer} from '@/lib/pulse';
type EmailConfig={configured:boolean;from_email:string|null;reply_to:string;message:string|null};
type Delivery={status:string;recipient:string;provider_id:string|null};
export function DraftEmail({draft}:{draft:Draft}){
 const [config,setConfig]=useState<EmailConfig|null>(null),[delivery,setDelivery]=useState<Delivery|null>(null),[recipient,setRecipient]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setConfig(null);setDelivery(null);setRecipient('');setReviewed(false);setError('');void Promise.all([pulse<EmailConfig>('/email/config'),pulse<Delivery|null>('/drafts/'+draft.id+'/delivery'),draft.customer_id?pulse<Customer>('/customers/'+draft.customer_id):Promise.resolve(null)]).then(([settings,result,customer])=>{if(active){setConfig(settings);setDelivery(result);setRecipient(result?.recipient||customer?.email||'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[draft.id]);
 useEffect(()=>{setReviewed(false);},[draft.content]);
 async function send(event:React.FormEvent){event.preventDefault();if(busy||!reviewed)return;setBusy(true);setError('');try{if(!delivery){await pulse<Draft>('/drafts/'+draft.id,{method:'PATCH',body:JSON.stringify({content:draft.content,status:'Approved'})});}const result=await pulse<Delivery>('/drafts/'+draft.id+'/send',{method:'POST',body:JSON.stringify({recipient,content:draft.content})});setDelivery(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(draft.kind!=='Follow-up email')return null;
 return <section className="cp-email-send" aria-label="Send drafted email"><h3><Mail size={18}/>Send to your customer</h3>{error&&<p className="cp-error-text" role="alert">{error}</p>}{delivery?.status==='Accepted'?<div role="status"><Check size={18}/><strong>Accepted by email provider for {delivery.recipient}</strong><p>Message reference: {delivery.provider_id}. Inbox delivery is not yet confirmed.</p></div>:<>{config?<><dl><div><dt>From</dt><dd>{config.from_email||'Verified sender not configured'}</dd></div><div><dt>Replies go to</dt><dd>{config.reply_to}</dd></div><div><dt>Subject</dt><dd>{draft.title}</dd></div></dl>{!config.configured&&<p role="status">{config.message}</p>}<form onSubmit={send}><label>Recipient email<input type="email" required maxLength={254} value={recipient} disabled={busy||!!delivery} onChange={e=>{setRecipient(e.target.value);setReviewed(false);}} placeholder="customer@company.com" autoComplete="off"/></label>{delivery&&<p>A previous attempt is pending. Retrying keeps the original email details and prevents duplicate sends.</p>}<label className="cp-email-confirm"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/><span>I have checked the recipient, draft content, and supporting sources.</span></label><p>Sending saves and approves the message you reviewed.</p><button className="cp-button" disabled={busy||!config.configured||!reviewed||!recipient.trim()}>{busy?<DotsRing size={17} className="cp-spin"/>:<Mail size={17}/>} {busy?'Sending…':'Approve and send email'}</button></form></>:!error&&<p role="status"><DotsRing size={18}/> Checking email setup…</p>}</>}</section>;
}
