'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity,LayoutDashboard,Users,MessageSquare,MessageCircleWarning,UploadCloud,Bell,FileBarChart,Settings,Sun,Moon,Menu,X,LogOut,ArrowUpRight} from 'lucide-react';
import {supabase} from '@/lib/api';
export const navigation=[{id:'overview',label:'Overview',Icon:LayoutDashboard},{id:'customers',label:'Customers',Icon:Users},{id:'intelligence',label:'Intelligence',Icon:MessageSquare},{id:'complaints',label:'Complaints',Icon:MessageCircleWarning},{id:'uploads',label:'Upload Center',Icon:UploadCloud},{id:'alerts',label:'Alerts',Icon:Bell},{id:'reports',label:'Reports',Icon:FileBarChart},{id:'settings',label:'Settings',Icon:Settings}];
export function PulseBrand(){return <Link href="/" className="cp-brand"><span><Activity size={23}/></span>ClientPulse<span className="cp-ai">AI</span></Link>;}
export function PulseShell({section,children}:{section:string;children:React.ReactNode}){
 const [dark,setDark]=useState(false),[open,setOpen]=useState(false),[email,setEmail]=useState('');const router=useRouter();
 useEffect(()=>{setDark(localStorage.getItem('cp-theme')==='dark');let active=true;supabase?.auth.getSession().then(({data})=>{if(!active)return;if(!data.session)router.replace('/login');else setEmail(data.session.user.email||'Your account');});if(!supabase)router.replace('/login');const sub=supabase?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')router.replace('/login');});return()=>{active=false;sub?.data.subscription.unsubscribe();};},[router]);
 function toggle(){setDark(!dark);localStorage.setItem('cp-theme',!dark?'dark':'light');}
 return <div className={`pulse ${dark?'cp-dark':''}`}><a className="cp-skip" href="#cp-main">Skip to content</a>{open&&<button className="cp-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`cp-sidebar ${open?'cp-open':''}`}><PulseBrand/><div className="cp-org"><span className="cp-avatar">CP</span><div><strong>Customer intelligence</strong><small>Your organization</small></div></div><span className="cp-nav-label">WORKSPACE</span><nav>{navigation.map(({id,label,Icon})=><Link href={id==='overview'?'/dashboard':'/dashboard/'+id} className={section===id?'cp-active':''} key={id} onClick={()=>setOpen(false)}><Icon size={18}/>{label}{id==='intelligence'&&<span className="cp-mini">AI</span>}</Link>)}</nav><div className="cp-sidebar-foot"><div className="cp-help"><span className="cp-mini">EVIDENCE FIRST</span><strong>Every signal has a source.</strong><p>See what happened. Decide what comes next.</p><Link href="/dashboard/uploads">Connect communications <ArrowUpRight size={15}/></Link></div><div className="cp-account"><span className="cp-avatar">{email.slice(0,1).toUpperCase()||'C'}</span><span title={email}>{email||'Checking session…'}</span><button aria-label="Sign out" className="cp-icon" onClick={async()=>{await supabase?.auth.signOut();router.replace('/login');}}><LogOut size={17}/></button></div></div></aside><div className="cp-main"><header className="cp-topbar"><button className="cp-icon cp-mobile" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><span>Workspace <span className="cp-separator">/</span> <strong>{navigation.find(n=>n.id===section)?.label||'Customer profile'}</strong></span><div><span className="cp-top-note">Customer signals. Connected.</span><button className="cp-icon" onClick={toggle} aria-label={dark?'Use light mode':'Use dark mode'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></div></header><main id="cp-main" className="cp-content">{children}</main><footer className="cp-footer">ClientPulse AI <span>Evidence-backed customer intelligence · Human decisions, supported.</span></footer></div></div>;
}
