'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowRight,Eye,EyeOff,LoaderCircle,ShieldCheck} from 'lucide-react';
import {supabase} from '@/lib/api';
import {PulseBrand} from './pulse-shell';
export default function PulseLogin(){
 const [mode,setMode]=useState<'login'|'signup'|'reset'|'update'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const router=useRouter();
 const [checking,setChecking]=useState(true);
 useEffect(()=>{let active=true,recovery=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery';const subscription=supabase?.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){recovery=true;setMode('update');setChecking(false);}});if(!supabase){setChecking(false);return;}void supabase.auth.getSession().then(({data})=>{if(!active)return;if(data.session&&!recovery){router.replace('/onboarding');return;}if(recovery)setMode('update');setChecking(false);}).catch(()=>{if(active)setChecking(false);});return()=>{active=false;subscription?.data.subscription.unsubscribe();};},[router]);
 async function google(){if(!supabase){setError('Supabase Auth is not configured.');return;}setBusy(true);setError('');try{const response=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+'/auth/v1/settings',{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!}});if(!response.ok)throw new Error('Unable to reach authentication.');const config=await response.json();if(!config.external?.google)throw new Error('Google sign-in needs to be enabled in Supabase. Email sign-in is available.');const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/auth/callback',skipBrowserRedirect:true}});if(error)throw error;if(data.url)location.assign(data.url);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function submit(event:React.FormEvent){event.preventDefault();if(!supabase){setError('Supabase Auth is not configured.');return;}setBusy(true);setError('');setNotice('');try{if(mode==='reset'){const result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/login'});if(result.error)throw result.error;setNotice('If your account exists, a reset link has been sent.');}else if(mode==='update'){const result=await supabase.auth.updateUser({password});if(result.error)throw result.error;router.push('/onboarding');}else if(mode==='signup'){const result=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/onboarding'}});if(result.error)throw result.error;if(result.data.session)router.push('/onboarding');else setNotice('Check your email to confirm your account, then sign in.');}else{const result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;router.push('/onboarding');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(checking)return <main className="pulse cp-auth"><div className="cp-auth-card"><LoaderCircle className="cp-spin"/><p>Checking your session…</p></div></main>;
 return <main className="pulse cp-auth"><div className="cp-auth-wrap"><PulseBrand/><section className="cp-auth-card"><span className="cp-eyebrow">CUSTOMER SIGNALS. CONNECTED.</span><h1 style={{marginTop:12}}>{mode==='signup'?'Create your account':mode==='reset'?'Reset your password':mode==='update'?'Choose a new password':'Welcome back.'}</h1><p>Sign in to understand your customers and act with the full context.</p>{error&&<div className="cp-notice cp-error" role="alert">{error}</div>}{notice&&<div className="cp-notice" role="status">{notice}</div>}{(mode==='login'||mode==='signup')&&<><button className="cp-button cp-secondary" disabled={busy} onClick={()=>void google()}><span aria-hidden="true" style={{fontWeight:700,color:'#4285f4',fontSize:18}}>G</span>Continue with Google</button><div className="cp-auth-divider">or use your email</div></>}<form onSubmit={submit}>{mode!=='update'&&<label>Email address<input autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@company.com" disabled={busy}/></label>}{mode!=='reset'&&<label>Password<div className="cp-auth-password"><input autoComplete={mode==='login'?'current-password':'new-password'} type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} placeholder="Enter your password" disabled={busy}/><button type="button" className="cp-icon" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>}{mode==='login'&&<button className="cp-text-button" type="button" onClick={()=>{setMode('reset');setError('');}}>Forgot password?</button>}<button className="cp-button" disabled={busy}>{busy?<LoaderCircle size={17} className="cp-spin"/>:<ArrowRight size={17}/>} {mode==='signup'?'Create account':mode==='reset'?'Send reset link':mode==='update'?'Save password':'Sign in'}</button></form><div className="cp-auth-toggle">{mode==='login'?'New to ClientPulse?':'Already have an account?'} <button onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setNotice('');}}>{mode==='login'?'Create an account':'Sign in'}</button></div></section><div className="cp-auth-footer"><ShieldCheck size={14} style={{display:'inline',verticalAlign:'middle',marginRight:6}}/>Private communications. Source-backed decisions.<p><Link href="/">Back to website</Link></p></div></div></main>;
}
