'use client';
import {DotsRing} from './ui/dots-ring';
import {WorkspaceGlow} from './workspace-glow';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity,LayoutDashboard,Users,MessageSquare,MessageCircleWarning,UploadCloud,Bell,FileBarChart,Settings,Sun,Moon,Menu,X,LogOut,ArrowUpRight} from 'lucide-react';
import {supabase} from '@/lib/api';
import {AccountMenu} from './account-menu';
import {useDialogFocus} from './use-dialog-focus';
import {pulse,Settings as WorkspaceSettings} from '@/lib/pulse';
export const navigation=[{id:'overview',label:'Dashboard',Icon:LayoutDashboard},{id:'customers',label:'Customers',Icon:Users},{id:'intelligence',label:'Intelligence',Icon:MessageSquare},{id:'complaints',label:'Complaints',Icon:MessageCircleWarning},{id:'uploads',label:'Upload Center',Icon:UploadCloud},{id:'alerts',label:'Alerts',Icon:Bell},{id:'reports',label:'Reports',Icon:FileBarChart},{id:'settings',label:'Settings',Icon:Settings}];
export function PulseBrand({href='/'}:{href?:string}){return <Link href={href} className="cp-brand"><span><Activity size={23}/></span>ClientPulse<span className="cp-ai">AI</span></Link>;}
export function PulseShell({section,children}:{section:string;children:React.ReactNode}){
 const [dark,setDark]=useState(false),[open,setOpen]=useState(false),[company,setCompany]=useState(''),[ready,setReady]=useState(false),[setupError,setSetupError]=useState('');const router=useRouter();const sidebarRef=useDialogFocus(open,()=>setOpen(false));const navRef=useRef<HTMLElement>(null);const [highlight,setHighlight]=useState({top:0,height:56,visible:false});
 function moveHighlight(element:HTMLElement){const nav=navRef.current;if(!nav)return;setHighlight({top:element.getBoundingClientRect().top-nav.getBoundingClientRect().top,height:element.offsetHeight,visible:true});}
 useEffect(()=>{setDark(localStorage.getItem('cp-theme')==='dark');let active=true;supabase?.auth.getSession().then(async({data})=>{if(!active)return;if(!data.session){router.replace('/login');return;}try{const settings=await pulse<WorkspaceSettings>('/settings');if(!active)return;if(settings.onboarding_required){router.replace('/onboarding');return;}setCompany(settings.name);setReady(true);}catch(e){if(active)setSetupError((e as Error).message);}});if(!supabase)router.replace('/login');const sub=supabase?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')router.replace('/login');});return()=>{active=false;sub?.data.subscription.unsubscribe();};},[router]);
 useEffect(()=>{const desktop=matchMedia('(min-width:961px)');const close=()=>{if(desktop.matches)setOpen(false);};desktop.addEventListener('change',close);return()=>desktop.removeEventListener('change',close);},[]);
 function toggle(){setDark(!dark);localStorage.setItem('cp-theme',!dark?'dark':'light');}
 if(!ready)return <main className="pulse cp-auth"><div className="cp-auth-card"><p role={setupError?'alert':'status'}>{setupError||<><DotsRing size={36}/><span>Opening your workspace…</span></>}</p>{setupError&&<button className="cp-button" onClick={()=>location.reload()}>Retry</button>}</div></main>;
 return <WorkspaceGlow><div className={`pulse ${dark?'cp-dark':''}`}><a className="cp-skip" href="#cp-main">Skip to content</a>{open&&<button className="cp-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside id="cp-sidebar" ref={sidebarRef} role={open?'dialog':undefined} aria-modal={open?true:undefined} aria-label="Workspace navigation" className={`cp-sidebar ${open?'cp-open':''}`}><PulseBrand href="/dashboard"/><div className="cp-org"><span className="cp-avatar">CP</span><div><strong>Customer intelligence</strong><small>{company}</small></div></div><span className="cp-nav-label">WORKSPACE</span><nav ref={navRef} className="cp-tracking-nav" onMouseLeave={()=>setHighlight(h=>({...h,visible:false}))}><span aria-hidden="true" className="cp-nav-highlight" style={{height:highlight.height,transform:`translateY(${highlight.top}px)`,opacity:highlight.visible?1:0}}/>{navigation.map(({id,label,Icon})=><Link href={id==='overview'?'/dashboard':'/dashboard/'+id} aria-current={section===id?'page':undefined} className={section===id?'cp-active':''} key={id} onMouseEnter={event=>moveHighlight(event.currentTarget)} onClick={()=>setOpen(false)}><Icon size={24}/>{label}{id==='intelligence'&&<span className="cp-mini">AI</span>}</Link>)}</nav><div className="cp-sidebar-foot"><button aria-label="Sign out" className="cp-sidebar-action" onClick={async()=>{await supabase?.auth.signOut();router.replace('/login');}}><LogOut size={24}/>Logout</button></div></aside><div className="cp-main"><header className="cp-topbar"><button className="cp-icon cp-mobile" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open} aria-controls="cp-sidebar">{open?<X/>:<Menu/>}</button><span>Workspace <span className="cp-separator">/</span> <strong>{navigation.find(n=>n.id===section)?.label||(section==='manual'?'User manual':'Customer profile')}</strong></span><div><button className="cp-icon" onClick={toggle} aria-label={dark?'Use light mode':'Use dark mode'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><AccountMenu company={company}/></div></header><main id="cp-main" className="cp-content">{children}</main></div></div></WorkspaceGlow>;
}
