'use client';
import { useEffect,useState,useRef } from 'react';
import { X, Download, FileText, ExternalLink } from 'lucide-react';
import { Evidence,EvidenceFile,fileBlob,download } from '@/lib/api';
export function SourceViewer({source,file,onClose}:{source?:Evidence;file:EvidenceFile;onClose:()=>void}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');const media=useRef<HTMLMediaElement>(null);
 useEffect(()=>{let cancelled=false;let objectUrl='';fileBlob('/files/'+file.id+'/content').then(blob=>{objectUrl=URL.createObjectURL(blob);if(!cancelled)setUrl(objectUrl);}).catch(e=>setError(e.message));return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[file.id]);
 useEffect(()=>{if(media.current&&source?.timestamp!=null)media.current.currentTime=source.timestamp;},[url,source]);
 return <div className="source-backdrop"><section className="source-panel" role="dialog" aria-modal="true" aria-label={'Source: '+file.name}><header><div><span className="overline">ORIGINAL EVIDENCE</span><h3>{file.name}</h3></div><button className="icon-button" onClick={onClose} aria-label="Close source"><X/></button></header><div className="source-meta"><span>{file.mime}</span><span>{(file.size/1024).toFixed(1)} KB</span>{source?.page&&<span>Page {source.page}</span>}{source?.timestamp!=null&&<span>{source.timestamp}s</span>}</div>{error&&<div className="error-banner">{error}</div>}{!url&&!error&&<div className="loading-card">Opening private evidence…</div>}{url&&<div className="source-preview">{file.mime==='application/pdf'?<iframe title={file.name} src={url+(source?.page?'#page='+source.page:'')}/>:file.mime.startsWith('image/')?<img src={url} alt={file.name}/>:file.mime.startsWith('video/')?<video ref={media as React.RefObject<HTMLVideoElement>} src={url} controls onLoadedMetadata={()=>{if(media.current&&source?.timestamp!=null)media.current.currentTime=source.timestamp;}}/>:file.mime.startsWith('audio/')?<audio ref={media as React.RefObject<HTMLAudioElement>} src={url} controls onLoadedMetadata={()=>{if(media.current&&source?.timestamp!=null)media.current.currentTime=source.timestamp;}}/>:file.mime.startsWith('text/')?<TextPreview url={url}/>:<div className="empty-state"><FileText/><p>This document is available as a download. Extracted passages appear below.</p></div>}</div>}{source&&<div className="source-excerpt"><span className="overline">REFERENCED PASSAGE {source.row?'· ROW '+source.row:''}</span><p>{source.content}</p><small>{source.extraction||'Source extraction'} · Evidence ID {source.id}</small></div>}{file.meta.limitations?.map(l=><div className="notice" key={l}>{l}</div>)}<button className="button secondary full" onClick={()=>download('/files/'+file.id+'/content',file.name).catch(e=>setError(e.message))}><Download size={15}/>Download original</button></section></div>;
}
function TextPreview({url}:{url:string}){const [text,setText]=useState('');useEffect(()=>{fetch(url).then(r=>r.text()).then(setText);},[url]);return <pre>{text.slice(0,30000)}</pre>;}
