import Link from 'next/link';
import {PulseShell} from '@/components/pulse-shell';
const chapters = [
 ['Getting started','Sign in with Google or your registered email and password. Enter your company name when prompted. Open the account icon at the top right for your identity, company settings, this manual, and Sign out.','/dashboard/settings'],
 ['Add customers','Open Customers and select Add customer. Save their details, then search the list to find them. Open a customer profile to review their communications, complaints, and risk factors.','/dashboard/customers'],
 ['Upload communications','Open Upload Center, select the customer when known, then drop files or click to browse. Supported formats: PDF, DOCX, TXT, CSV, EML, PNG, JPG, WEBP, MP3, WAV. Maximum size: 25 MB per file. Audio is transcribed and documents or screenshots are extracted for analysis.','/dashboard/uploads'],
 ['Processing and support tickets','Upload completion means the file was received; wait for processing to finish before asking about it. Check the Processing column. Assign the correct customer if identity review is needed. For a failed job, read the error and use Retry. To add a support ticket, choose a customer, enter the subject and actual communication, optionally include its date, and select Save ticket.','/dashboard/uploads'],
 ['Dashboard and automatic scores','Dashboard shows customer counts, complaints, alerts, and recent activity. Scores update automatically from recorded evidence. Resolved cases stop contributing active risk; a promise to fix a problem is not a completed resolution. Low: 0-29; Moderate: 30-59; High: 60-79; Critical: 80-100. Scores prioritize review and are not a percentage chance of churn.','/dashboard'],
 ['Complaints and alerts','Review correlated complaints and their supporting communications. Verify the evidence before recording a resolution using the case controls. Alerts highlight signals such as cancellation statements, repeated follow-ups, or overdue commitments. Open the linked customer to understand the context.','/dashboard/complaints'],
 ['Ask the assistant','Open Intelligence and choose a customer for a focused answer, or ask across your organization. Try: Which complaints remain unresolved? Click citations beneath the answer to inspect original evidence. If information is missing, upload the relevant communication and wait for processing. Verify important AI conclusions.','/dashboard/intelligence'],
 ['Drafts and PDF reports','Open Reports, select a customer if needed and a draft type, then Generate draft. Inspect citations, edit the text, and Save draft. Approve records your review. For follow-up emails, enter the recipient in the sending section, check the content and sources, tick the review confirmation, and select Send email. The company sender appears under From; replies go to your signed-in email. Resend acceptance does not confirm inbox delivery. Select PDF to download reports.','/dashboard/reports'],
 ['Company settings and navigation','Use My Account to open Company settings and update the company name or retention period. Delete expired data permanently removes expired records after confirmation. Use the moon or sun button to change theme. On small screens, open the menu to navigate. The workspace logo returns to Dashboard.','/dashboard/settings'],
 ['Troubleshooting','For upload problems, check file format and size. For incomplete answers, check processing status and customer assignment. Retry a failed request once; if it persists, give your administrator the page, action, time, and error message. Only upload communications you are authorized to process, and never upload passwords or API keys.','/dashboard/uploads'],
];
export default function UserManual(){return <PulseShell section="manual"><div className="cp-manual"><header><span className="cp-eyebrow">MY ACCOUNT / HELP</span><h1>How to use ClientPulse</h1><p>Follow this guide to set up your workspace and turn communications into source-backed answers.</p></header><nav className="cp-panel cp-manual-index" aria-label="Manual contents"><h2>Find an instruction</h2>{chapters.map(([title],index)=><a key={title} href={'#manual-'+index}>{index+1}. {title}</a>)}</nav>{chapters.map(([title,text,href],index)=><section className="cp-panel cp-manual-chapter" id={'manual-'+index} key={title}><h2>{index+1}. {title}</h2><p>{text}</p><Link className="cp-button cp-secondary" href={href}>Open this section</Link></section>)}</div></PulseShell>;}
