'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {ArrowRight,ShieldCheck,UserRound,LogOut} from 'lucide-react';
import {AppShell} from '@/components/app-shell';
import {supabase} from '@/lib/api';
export default function Account(){
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getUser().then(({data,error})=>{if(data.user){setEmail(data.user.email||'');setName(data.user.user_metadata.display_name||'');setSignedIn(true);}else if(error)setNotice('Sign in to manage your account.');setLoading(false);});},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const {error}=await supabase.auth.updateUser({data:{display_name:name.trim()}});setNotice(error?error.message:'Your profile has been saved.');setBusy(false);}
 return <AppShell><header className="app-topbar"><Link href="/dashboard">Dashboard / Account</Link><span className="system-state"><ShieldCheck size={14}/>Supabase authentication</span></header><div className="dashboard-content"><div className="page-heading"><div><span className="overline">YOUR ACCOUNT</span><h1>Profile & settings</h1><p>Manage your profile and secure your account.</p></div></div>{loading?<div className="loading-card">Loading your account…</div>:signedIn?<><form className="panel settings-form" onSubmit={save}><h2>Your profile</h2><label>Display name<input value={name} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Email address<input value={email} type="email" disabled/></label><button className="button primary" disabled={busy}>{busy?'Saving…':'Save profile'}<ArrowRight size={15}/></button></form><section className="panel settings-form"><h2>Account security</h2><p>Request a secure password reset link to your registered email address.</p><button className="button secondary" disabled={busy} onClick={async()=>{if(!supabase)return;setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/login'});setNotice(error?error.message:'Password reset link sent. Check your email.');setBusy(false);}}>Send password reset link <ShieldCheck size={15}/></button><div style={{marginTop:20}}><button className="text-link" onClick={async()=>{await supabase?.auth.signOut();location.assign('/login');}}>Sign out <LogOut size={15}/></button></div></section></>:<section className="empty-state"><UserRound size={31}/><h3>Sign in to manage your profile.</h3><p>Sign in with your registered email or Google account.</p><Link href="/login" className="button primary">Sign in <ArrowRight size={15}/></Link></section>}{notice&&<div role="status" className="notice">{notice}</div>}</div></AppShell>;
}
